name: Subscription Update

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/60 * * * *'

  #workflow_dispatch:
jobs:
  update-vmess:
    runs-on: ubuntu-latest

    steps:
      - name: Check The Code
        uses: actions/checkout@v2
      - name: Get Files
        run: |
          curl -o vmess.txt -LJO "https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/base64/vmess"
          curl -o vless.txt -LJO "https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/base64/vless"
      - name: Push And Update Files
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "ðŸš€Servers Updated - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S') Asia/Tehran"
          git push
